---

- name: "Apache installation using docker"
  hosts: prod     # On the group Prod
  become: true    # To use privilege escalation

  vars_files:     # Location variable password 
    - files/secrets/credentials.yml  

  pre_tasks:
    - name: Install packages 
      package: name='{{ item }}' state=present # Loop on package
      when: ansible_distribution == "CentOS"   # To specify distrib
      loop:
        - epel-release
        - wget
        - git

    - name: download pip script                
      get_url:
        url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
        dest: /tmp/get-pip.py

    - name: install python-pip
      command: python2.7 /tmp/get-pip.py

    - name: Install docker python
      pip: name=docker-py
  


  tasks:
    - name: Copy website file template
      template:
        src: index.html.j2
        dest: /home/admin/index.html

    - name: Create Apache container
      docker_container:
        name: webapp
        image: httpd
        ports:         # Port binding
          - "80:80"
        volumes:       # Volume shared host/docker
          - /home/admin/index.html:/usr/local/apache2/htdocs/index.html
